export const GITHUB_URL = 'https://github.com/rohchakr'
export const LINKEDIN_URL = 'https://www.linkedin.com/in/rohchakr'
export const TWITTER_URL = 'https://twitter.com/rohchakr'
export const INSTAGRAM_URL = 'https://www.instagram.com/rohchakr'
export const FACEBOOK_URL = 'https://www.facebook.com/rcredhit'