name: Full Build and Deploy  ## Workflow

on:
  push:
    branches:
      - source

defaults: 
  run:
    shell: bash

jobs:
  main-job:

    name: Deploy Job
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Configure Github user
        env:
          USER_NAME: ${{ secrets.GIT_USER_NAME }}
          USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config user.email "$USER_EMAIL"
          git config user.name "$USER_NAME"
      - name: Install, Build and Deploy
        run: |
          npm install
          NODE_DEBUG=gh-pages npm run deploy