name: Full Build and Deploy  ## Workflow

on:
  push:
    branches:
      - source

defaults: 
  run:
    shell: bash

jobs:
  main-job:

    name: Deploy Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
          CLEAN: true